// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cluster_message.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActorMessage 对齐 internal/protocol.Message 的核心字段。
type ActorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           uint32                 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Act           uint32                 `protobuf:"varint,2,opt,name=act,proto3" json:"act,omitempty"`
	Error         uint32                 `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Index         uint32                 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorMessage) Reset() {
	*x = ActorMessage{}
	mi := &file_cluster_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorMessage) ProtoMessage() {}

func (x *ActorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorMessage.ProtoReflect.Descriptor instead.
func (*ActorMessage) Descriptor() ([]byte, []int) {
	return file_cluster_message_proto_rawDescGZIP(), []int{0}
}

func (x *ActorMessage) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *ActorMessage) GetAct() uint32 {
	if x != nil {
		return x.Act
	}
	return 0
}

func (x *ActorMessage) GetError() uint32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ActorMessage) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ActorMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ActorPID 对齐 pkg/actor.PID 的核心字段。
type ActorPID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       uint64                 `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorName     string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorPID) Reset() {
	*x = ActorPID{}
	mi := &file_cluster_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorPID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorPID) ProtoMessage() {}

func (x *ActorPID) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorPID.ProtoReflect.Descriptor instead.
func (*ActorPID) Descriptor() ([]byte, []int) {
	return file_cluster_message_proto_rawDescGZIP(), []int{1}
}

func (x *ActorPID) GetActorId() uint64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *ActorPID) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *ActorPID) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// ClusterMessage 用于节点间投递到指定 actor。
type ClusterMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TraceId   string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CreatedAt int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// actor 侧需要处理的消息内容。
	Message *ActorMessage `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 新字段：完整 PID 信息（推荐使用）。
	TargetPid     *ActorPID `protobuf:"bytes,4,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	SourcePid     *ActorPID `protobuf:"bytes,5,opt,name=source_pid,json=sourcePid,proto3" json:"source_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage) Reset() {
	*x = ClusterMessage{}
	mi := &file_cluster_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage) ProtoMessage() {}

func (x *ClusterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage.ProtoReflect.Descriptor instead.
func (*ClusterMessage) Descriptor() ([]byte, []int) {
	return file_cluster_message_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ClusterMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ClusterMessage) GetMessage() *ActorMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClusterMessage) GetTargetPid() *ActorPID {
	if x != nil {
		return x.TargetPid
	}
	return nil
}

func (x *ClusterMessage) GetSourcePid() *ActorPID {
	if x != nil {
		return x.SourcePid
	}
	return nil
}

var File_cluster_message_proto protoreflect.FileDescriptor

const file_cluster_message_proto_rawDesc = "" +
	"\n" +
	"\x15cluster_message.proto\x12\acluster\"r\n" +
	"\fActorMessage\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\rR\x03cmd\x12\x10\n" +
	"\x03act\x18\x02 \x01(\rR\x03act\x12\x14\n" +
	"\x05error\x18\x03 \x01(\rR\x05error\x12\x14\n" +
	"\x05index\x18\x04 \x01(\rR\x05index\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"]\n" +
	"\bActorPID\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\x04R\aactorId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"\xdf\x01\n" +
	"\x0eClusterMessage\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12/\n" +
	"\amessage\x18\x03 \x01(\v2\x15.cluster.ActorMessageR\amessage\x120\n" +
	"\n" +
	"target_pid\x18\x04 \x01(\v2\x11.cluster.ActorPIDR\ttargetPid\x120\n" +
	"\n" +
	"source_pid\x18\x05 \x01(\v2\x11.cluster.ActorPIDR\tsourcePidB\vZ\t.;clusterb\x06proto3"

var (
	file_cluster_message_proto_rawDescOnce sync.Once
	file_cluster_message_proto_rawDescData []byte
)

func file_cluster_message_proto_rawDescGZIP() []byte {
	file_cluster_message_proto_rawDescOnce.Do(func() {
		file_cluster_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_message_proto_rawDesc), len(file_cluster_message_proto_rawDesc)))
	})
	return file_cluster_message_proto_rawDescData
}

var file_cluster_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cluster_message_proto_goTypes = []any{
	(*ActorMessage)(nil),   // 0: cluster.ActorMessage
	(*ActorPID)(nil),       // 1: cluster.ActorPID
	(*ClusterMessage)(nil), // 2: cluster.ClusterMessage
}
var file_cluster_message_proto_depIdxs = []int32{
	0, // 0: cluster.ClusterMessage.message:type_name -> cluster.ActorMessage
	1, // 1: cluster.ClusterMessage.target_pid:type_name -> cluster.ActorPID
	1, // 2: cluster.ClusterMessage.source_pid:type_name -> cluster.ActorPID
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cluster_message_proto_init() }
func file_cluster_message_proto_init() {
	if File_cluster_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_message_proto_rawDesc), len(file_cluster_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_message_proto_goTypes,
		DependencyIndexes: file_cluster_message_proto_depIdxs,
		MessageInfos:      file_cluster_message_proto_msgTypes,
	}.Build()
	File_cluster_message_proto = out.File
	file_cluster_message_proto_goTypes = nil
	file_cluster_message_proto_depIdxs = nil
}
